apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: app-b-{{ .Values.apps.namespace }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    path: app-B/helm
    repoURL: https://github.com/Kazeheki/argo-cd-poc.git
    targetRevision: HEAD
  destination:
    namespace: {{ .Values.apps.namespace }}
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
