apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: my-example-app-with-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    path: infra/helm
    repoURL: https://github.com/Kazeheki/argo-cd-poc.git
    targetRevision: HEAD
    helm: {}
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
