### Register repository for sealed secrets
 
apiVersion: v1
kind: Secret
metadata:
  name: sealed-secrets-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: 'https://bitnami-labs.github.io/sealed-secrets'
  name: sealed-secrets
  type: helm
 
---
 
### Add Argo Application to manage Sealed Secrets Application
 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: ''
    name: in-cluster
  source:
    path: ''
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: 1.16.1
    chart: sealed-secrets
    helm:
      values: |-
        fullnameOverride:
          sealed-secrets-controller
  project: default
  syncPolicy:
    automated:
        prune: true
        selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m